import type { Conversation } from "@/types/chat";

/** Clearly labeled demo history. Replaced by Supabase in a later phase. */
export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "demo-today-1",
    title: "Flutter login sahifasi",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mode: "code",
    aiMode: "coding",
    modelId: "nodir-balanced",
    messages: [],
    isDemo: true,
  },
  {
    id: "demo-today-2",
    title: "Ingliz tilini o'rganish",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    mode: "translate",
    aiMode: "study",
    modelId: "nodir-fast",
    messages: [],
    isDemo: true,
  },
  {
    id: "demo-yesterday-1",
    title: "Portfolio uchun g'oya",
    createdAt: new Date(Date.now() - 86_400_000).toISOString(),
    updatedAt: new Date(Date.now() - 86_400_000).toISOString(),
    mode: "write",
    aiMode: "writing",
    modelId: "nodir-balanced",
    messages: [],
    isDemo: true,
    favorite: true,
  },
  {
    id: "demo-yesterday-2",
    title: "Python kodini tushuntirish",
    createdAt: new Date(Date.now() - 90_000_000).toISOString(),
    updatedAt: new Date(Date.now() - 90_000_000).toISOString(),
    mode: "code",
    aiMode: "coding",
    modelId: "nodir-advanced",
    messages: [],
    isDemo: true,
  },
  {
    id: "demo-older-1",
    title: "Web sayt loyihasi",
    createdAt: new Date(Date.now() - 864_000_000).toISOString(),
    updatedAt: new Date(Date.now() - 864_000_000).toISOString(),
    mode: "chat",
    aiMode: "general",
    modelId: "nodir-balanced",
    messages: [],
    isDemo: true,
  },
];
